// Generated by https://quicktype.io

export interface GetGames {
    gameId:      string;
    title:       string;
    picture:     string;
    platform:    string;
    releaseDate: string;
    description: string;
}
