// Generated by https://quicktype.io

export interface iuser {
    name: string;
    email: string;
    passwordHash: string;
    role: Role;
    _id: string;
    createdAt: Date;
}


export enum Role {
    Admin = "admin",
    Client = "client",
}