import { HandleClientProvider } from '@/context/HandleClientProvider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sign in | Register Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <HandleClientProvider>
        <body className={inter.className}>
          {children}
        </body>
      </HandleClientProvider>
    </html>
  )
}
